export const NATIONALITIES: string[] = [
  'Filipino',
  'Afghan',
  'Albanian',
  'Algerian',
  'American',
  'Andorran',
  'Angolan',
  'Antiguan and Barbudan',
  'Argentine',
  'Armenian',
  'Australian',
  'Austrian',
  'Azerbaijani',
  'Bahamian',
  'Bahraini',
  'Bangladeshi',
  'Barbadian',
  'Belarusian',
  'Belgian',
  'Belizean',
  'Beninese',
  'Bhutanese',
  'Bolivian',
  'Bosnian and Herzegovinian',
  'Botswanan',
  'Brazilian',
  'British',
  'Bruneian',
  'Bulgarian',
  'Burkinabe',
  'Burmese',
  'Burundian',
  'Cabo Verdean',
  'Cambodian',
  'Cameroonian',
  'Canadian',
  'Central African',
  'Chadian',
  'Chilean',
  'Chinese',
  'Colombian',
  'Comoran',
  'Congolese (Congo-Brazzaville)',
  'Congolese (Congo-Kinshasa)',
  'Costa Rican',
  'Croatian',
  'Cuban',
  'Cypriot',
  'Czech',
  'Danish',
  'Djiboutian',
  'Dominican',
  'Dutch',
  'East Timorese',
  'Ecuadorian',
  'Egyptian',
  'Emirati',
  'Equatorial Guinean',
  'Eritrean',
  'Estonian',
  'Eswatini (Swazi)',
  'Ethiopian',
  'Fijian',
  'Finnish',
  'French',
  'Gabonese',
  'Gambian',
  'Georgian',
  'German',
  'Ghanaian',
  'Greek',
  'Grenadian',
  'Guatemalan',
  'Guinean',
  'Guinea-Bissauan',
  'Guyanese',
  'Haitian',
  'Honduran',
  'Hungarian',
  'Icelander',
  'Indian',
  'Indonesian',
  'Iranian',
  'Iraqi',
  'Irish',
  'Israeli',
  'Italian',
  'Ivorian',
  'Jamaican',
  'Japanese',
  'Jordanian',
  'Kazakhstani',
  'Kenyan',
  'Kiribati',
  'Korean (North)',
  'Korean (South)',
  'Kuwaiti',
  'Kyrgyz',
  'Lao',
  'Latvian',
  'Lebanese',
  'Lesotho',
  'Liberian',
  'Libyan',
  'Liechtenstein',
  'Lithuanian',
  'Luxembourgish',
  'Madagascan',
  'Malawian',
  'Malaysian',
  'Maldivian',
  'Malian',
  'Maltese',
  'Marshallese',
  'Mauritanian',
  'Mauritian',
  'Mexican',
  'Micronesian',
  'Moldovan',
  'Monacan',
  'Mongolian',
  'Montenegrin',
  'Moroccan',
  'Mozambican',
  'Namibian',
  'Nauruan',
  'Nepalese',
  'New Zealander',
  'Nicaraguan',
  'Nigerien',
  'Nigerian',
  'North Macedonian',
  'Norwegian',
  'Omani',
  'Pakistani',
  'Palauan',
  'Palestinian',
  'Panamanian',
  'Papua New Guinean',
  'Paraguayan',
  'Peruvian',
  'Polish',
  'Portuguese',
  'Qatari',
  'Romanian',
  'Russian',
  'Rwandan',
  'Saint Lucian',
  'Salvadoran',
  'Samoan',
  'San Marinese',
  'Sao Tomean',
  'Saudi Arabian',
  'Senegalese',
  'Serbian',
  'Seychellois',
  'Sierra Leonean',
  'Singaporean',
  'Slovak',
  'Slovenian',
  'Solomon Islander',
  'Somali',
  'South African',
  'South Sudanese',
  'Spanish',
  'Sri Lankan',
  'Sudanese',
  'Surinamese',
  'Swedish',
  'Swiss',
  'Syrian',
  'Taiwanese',
  'Tajik',
  'Tanzanian',
  'Thai',
  'Togolese',
  'Tongan',
  'Trinidadian and Tobagonian',
  'Tunisian',
  'Turkish',
  'Turkmen',
  'Tuvaluan',
  'Ugandan',
  'Ukrainian',
  'Uruguayan',
  'Uzbek',
  'Vanuatu',
  'Vatican',
  'Venezuelan',
  'Vietnamese',
  'Yemeni',
  'Zambian',
  'Zimbabwean',
];

export const COUNTRIES: string[] = [
  'Philippines',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo (Brazzaville)',
  'Congo (Kinshasa)',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const PORTS_OF_ENTRY: string[] = [
  'Manila — Ninoy Aquino International Airport (MNL)',
  'Clark / Angeles — Clark International Airport (CRK)',
  'Cebu / Lapu-Lapu — Mactan-Cebu International Airport (CEB)',
  'Davao — Francisco Bangoy International Airport (DVO)',
  'Kalibo — Kalibo International Airport (KLO)',
  'Iloilo — Iloilo International Airport (ILO)',
  'Puerto Princesa — Puerto Princesa International Airport (PPS)',
  'Panglao / Bohol — Bohol-Panglao International Airport (TAG)',
  'Laoag — Laoag International Airport (LAO)',
  'Subic Bay — Subic Bay International Airport (SFS)',
  'Zamboanga — Zamboanga International Airport (ZAM)',
  'General Santos — General Santos International Airport (GES)',
  'Cagayan de Oro — Laguindingan International Airport (CGY)',
  'Bacolod / Silay — Bacolod-Silay Airport (BCD)',
  'Bicol / Legazpi — Bicol International Airport (DRP)',
  'Caticlan / Boracay — Godofredo P. Ramos Airport (MPH)',
  'Port of Manila (Sea Port)',
  'Port of Cebu (Sea Port)',
  'Port of Batangas (Sea Port)',
  'Port of Subic (Sea Port)',
  'Port of Zamboanga (Sea Port)',
  'Port of Davao (Sea Port)',
];

export const ACADEMIC_YEARS: string[] = [
  '2026-2027',
  '2025-2026',
  '2024-2025',
  '2023-2024',
  '2022-2023',
  '2021-2022',
  '2020-2021',
  '2027-2028',
  '2028-2029',
  '2029-2030',
  '2030-2031',
];

export const REPORTING_YEARS: string[] = [
  '2026',
  '2025',
  '2024',
  '2023',
  '2022',
  '2021',
  '2020',
  '2027',
  '2028',
  '2029',
  '2030',
];

export const COMPANION_RELATIONSHIPS: string[] = [
  'Parent',
  'Legal Guardian',
  'Grandparent',
  'Aunt / Uncle',
  'Brother / Sister (Sibling)',
  'Cousin',
  'Relative',
  'Teacher / Chaperone',
  'Tour Leader / Escort',
  'Family Friend',
  'Other',
];

export type Field = { key:string; label:string; type?:string; required?:boolean; options?:string[] };
export type Section = { title:string; fields:Field[] };
const f=(key:string,label:string,type='text',required=true,options?:string[]):Field=>({key,label,type,required,options});
const personal:Section={title:'Personal information',fields:[f('firstName','Given name'),f('lastName','Last name'),f('birthDate','Date of birth','date'),f('nationality','Nationality','select',true,NATIONALITIES),f('email','Email address','email'),f('phone','Contact number','tel')]};
const passport:Section={title:'Passport information',fields:[f('passportNumber','Passport number'),f('passportCountry','Issuing country','select',true,COUNTRIES),f('passportExpiry','Passport expiry date','date')]};
const address:Section={title:'Philippine residential address',fields:[f('street','House / unit, building, street'),f('barangay','Barangay'),f('city','City / municipality'),f('province','Province'),f('postalCode','Postal code')]};
const travel:Section={title:'Travel information',fields:[f('travelDate','Travel date','date'),f('flightNumber','Flight / vessel number'),f('origin','Country of origin','select',true,COUNTRIES),f('destination','Country of destination','select',true,COUNTRIES),f('port','Port of arrival / departure','select',true,PORTS_OF_ENTRY)]};
const application:Section={title:'Application information',fields:[f('purpose','Purpose of application'),f('remarks','Additional information','textarea',false)]};
const school:Section={title:'School and enrollment',fields:[f('schoolName','School name'),f('schoolAddress','School address'),f('course','Course / program'),f('studentNumber','Student number'),f('schoolYear','Academic year','select',true,ACADEMIC_YEARS),f('enrollmentDate','Enrollment date','date')]};
const docs=['Passport bio page','Supporting documents'];
export const services = [
{id:'etravel',name:'eTravel',category:'Travel',icon:'plane',description:'Register your arrival or departure and keep your travel record in one place.',sections:[{title:'Journey details',fields:[f('direction','Travel direction','select',true,['Arrival','Departure']),f('transport','Mode of travel','select',true,['Air','Sea'])]},personal,passport,travel,address],documents:['Passport bio page']},
{id:'visa-waiver',name:'Visa waiver',category:'Stay',icon:'globe',description:'Apply for a visa waiver with a guided application.',sections:[personal,passport,travel,address,application],documents:docs},
{id:'student-visa',name:'Student visa conversion',category:'Study',icon:'graduation',description:'Submit your student visa conversion and enrollment details.',sections:[personal,passport,travel,address,school,application],documents:[...docs,'Facial image','Enrollment certificate']},
{id:'study-permit',name:'Special study permit',category:'Study',icon:'book',description:'Apply for a permit for your studies in the Philippines.',sections:[personal,passport,travel,address,school,application],documents:[...docs,'Facial image','Enrollment certificate']},
{id:'cruise-waiver',name:'Cruise visa waiver',category:'Travel',icon:'ship',description:'Manage a cruise application and upload passenger manifests.',sections:[personal,passport,travel,address,{title:'Vessel and voyage',fields:[f('vesselName','Vessel name'),f('imoNumber','IMO number'),f('voyageNumber','Voyage number'),f('company','Company name'),f('representative','Authorized representative')]},application],documents:[...docs,'Passenger manifest (.xlsx)']},
{id:'accreditation',name:'Accreditation',category:'Organization',icon:'building',description:'Submit your organization’s accreditation application.',sections:[personal,travel,address,{title:'Company information',fields:[f('company','Company name'),f('registrationNumber','Company registration number'),f('companyAddress','Company address')]},application],documents:['Facial image','Company registration','Supporting documents']},
{id:'annual-report',name:'Annual report',category:'Stay',icon:'calendar',description:'Complete your annual report with your ACR I-Card information.',sections:[personal,passport,address,{title:'ACR I-Card information',fields:[f('acrNumber','ACR I-Card number'),f('acrExpiry','ACR I-Card expiry','date'),f('reportYear','Reporting year','select',true,REPORTING_YEARS)]},application],documents:[...docs,'Facial image','ACR I-Card']},
{id:'school-registration',name:'Existing school registration',category:'Organization',icon:'school',description:'Register your school, courses, and liaison officer.',sections:[{title:'School information',fields:[f('schoolName','School name'),f('schoolAddress','School address'),f('courses','Courses offered','textarea'),f('accreditationNumber','Accreditation number'),f('accreditationExpiry','Accreditation expiry','date')]},{title:'Liaison officer',fields:[f('firstName','Given name'),f('lastName','Last name'),f('email','Email address','email'),f('phone','Contact number','tel')]}],documents:['School accreditation','Supporting documents']},
{id:'dual-citizenship',name:'Dual citizenship',category:'Citizenship',icon:'flag',description:'Apply with your personal, passport, and dependent information.',sections:[personal,passport,address,{title:'Dependent information',fields:[f('dependents','Dependents — names, birth dates, and relationship (or None)','textarea')]},application],documents:[...docs,'Facial image','Citizenship documents']},
{id:'weg',name:'Waiver of exclusion grounds',category:'Travel',icon:'users',description:'Provide travel, companion, and parent or guardian information.',sections:[personal,passport,travel,{title:'Companion and legal guardian',fields:[f('companionName','Companion’s full name'),f('companionRelationship','Relationship to traveler','select',true,COMPANION_RELATIONSHIPS),f('guardianName','Parent / legal guardian’s full name'),f('guardianNationality','Parent / guardian’s nationality','select',true,NATIONALITIES),f('guardianPassport','Parent / guardian’s passport number'),f('guardianPassportExpiry','Parent / guardian’s passport expiry','date')]},application],documents:[...docs,'Facial image','Parent / guardian passport','Proof of relationship']}
];
export type Application={id:string;service:string;status:string;data:Record<string,string>;created:string;updated:string;version:number;owner?:string};
export const validateApplication=(service:string,data:Record<string,string>)=>{
 const s=services.find(s=>s.id===service);if(!s)return ['Unknown service'];
 return s.sections.flatMap(s=>s.fields).flatMap(f=>{
 const value=data[f.key]?.trim();if(!value)return f.required?[f.label]:[];
 if((f.key==='passportNumber'||f.key==='guardianPassport')&&value.length!==9)return [f.label+' must be exactly 9 characters'];
 if(f.options&&!f.options.includes(value))return [f.label+' (invalid option)'];
 if(f.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))return [f.label+' (invalid email)'];
 if(f.type==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(value))))return [f.label+' (invalid date)'];
 if(f.key==='birthDate'&&value>new Date().toISOString().slice(0,10))return ['Date of birth cannot be in the future'];
 if(f.type==='number'&&!/^\d+$/.test(value))return [f.label+' (must be a number)'];
 return [];
 });
};
